In [2]:
import pandas as pd

In [3]:
nifty50_all_data = pd.read_csv("E:\\My Projects\\Stock price prediction\\Data set\\NIFTY50_all.csv")

In [11]:
nifty50_all_data

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
0,2007-11-27,MUNDRAPORT,EQ,440.00,770.00,1050.00,770.00,959.00,962.90,984.72,27294366,2.687719e+15,NaN,9859619.0,0.3612
1,2007-11-28,MUNDRAPORT,EQ,962.90,984.00,990.00,874.00,885.00,893.90,941.38,4581338,4.312765e+14,NaN,1453278.0,0.3172
2,2007-11-29,MUNDRAPORT,EQ,893.90,909.00,914.75,841.00,887.00,884.20,888.09,5124121,4.550658e+14,NaN,1069678.0,0.2088
3,2007-11-30,MUNDRAPORT,EQ,884.20,890.00,958.00,890.00,929.00,921.55,929.17,4609762,4.283257e+14,NaN,1260913.0,0.2735
4,2007-12-03,MUNDRAPORT,EQ,921.55,939.75,995.00,922.00,980.00,969.30,965.65,2977470,2.875200e+14,NaN,816123.0,0.2741
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235187,2021-04-26,ZEEL,EQ,188.00,190.60,191.10,185.10,186.70,186.40,187.35,8542755,1.600451e+14,52374.0,2340188.0,0.2739
235188,2021-04-27,ZEEL,EQ,186.40,188.00,192.95,186.80,188.80,188.15,189.41,14247767,2.698636e+14,73673.0,5425957.0,0.3808
235189,2021-04-28,ZEEL,EQ,188.15,188.80,190.60,187.10,188.95,189.10,188.85,8429439,1.591917e+14,44056.0,2413974.0,0.2864
235190,2021-04-29,ZEEL,EQ,189.10,190.80,191.65,186.00,186.60,186.55,187.44,9483009,1.777471e+14,60932.0,2744472.0,0.2894
235191,2021-04-30,ZEEL,EQ,186.55,185.30,190.95,183.65,185.00,185.60,187.53,11435285,2.144440e+14,62607.0,3323909.0,0.2907

1.How many rows and columns are present in the dataset?

In [4]:
print("Total columns = ",nifty50_all_data.shape[1])
print("Total rows = ",nifty50_all_data.shape[0])

Total columns =  15
Total rows =  235192

2.What are the data types of each column?

In [5]:
nifty50_all_data.dtypes

Date                   object
Symbol                 object
Series                 object
Prev Close            float64
Open                  float64
High                  float64
Low                   float64
Last                  float64
Close                 float64
VWAP                  float64
Volume                  int64
Turnover              float64
Trades                float64
Deliverable Volume    float64
%Deliverble           float64
dtype: object

3.How many unique stock symbols are available?

In [9]:
uniqueSymbols = nifty50_all_data["Symbol"].unique()

print("<-----Unique symbols name----->")
for val in uniqueSymbols:
    print(val,end=' , ')

<-----Unique symbols name----->
MUNDRAPORT , ADANIPORTS , ASIANPAINT , UTIBANK , AXISBANK , BAJAJ-AUTO , BAJAJFINSV , BAJAUTOFIN , BAJFINANCE , BHARTI , BHARTIARTL , BPCL , BRITANNIA , CIPLA , COALINDIA , DRREDDY , EICHERMOT , GAIL , GRASIM , HCLTECH , HDFC , HDFCBANK , HEROHONDA , HEROMOTOCO , HINDALC0 , HINDALCO , HINDLEVER , HINDUNILVR , ICICIBANK , INDUSINDBK , INFOSYSTCH , INFY , IOC , ITC , JSWSTL , JSWSTEEL , KOTAKMAH , KOTAKBANK , LT , M&M , MARUTI , NESTLEIND , NTPC , ONGC , POWERGRID , RELIANCE , SBIN , SHREECEM , SUNPHARMA , TELCO , TATAMOTORS , TISCO , TATASTEEL , TCS , TECHM , TITAN , ULTRACEMCO , UNIPHOS , UPL , SESAGOA , SSLT , VEDL , WIPRO , ZEETELE , ZEEL ,

4.What is the date range of the dataset (earliest and latest date)?

In [7]:
nifty50_all_data.groupby('Symbol')["Date"].agg(earliest_date = "min" , latest_date = "max")

           earliest_date latest_date
Symbol
ADANIPORTS    2012-01-17  2021-04-30
ASIANPAINT    2000-01-03  2021-04-30
AXISBANK      2007-08-16  2021-04-30
BAJAJ-AUTO    2008-05-26  2021-04-30
BAJAJFINSV    2008-05-26  2021-04-30
...                  ...         ...
UTIBANK       2000-01-03  2007-08-14
VEDL          2015-05-07  2021-04-30
WIPRO         2000-01-03  2021-04-30
ZEEL          2007-02-28  2021-04-30
ZEETELE       2000-01-03  2007-02-27

[65 rows x 2 columns]

5.How many missing values are present in each column?

In [8]:
nifty50_all_data.isnull().sum()

Date                       0
Symbol                     0
Series                     0
Prev Close                 0
Open                       0
High                       0
Low                        0
Last                       0
Close                      0
VWAP                       0
Volume                     0
Turnover                   0
Trades                114848
Deliverable Volume     16077
%Deliverble            16077
dtype: int64

6.Are there any negative values in numerical columns?

In [46]:
numeric = nifty50_all_data.select_dtypes(include="number")

negative = (numeric < 0).sum()

print(negative)

Prev Close            0
Open                  0
High                  0
Low                   0
Last                  0
Close                 0
VWAP                  0
Volume                0
Turnover              0
Trades                0
Deliverable Volume    0
%Deliverble           0
dtype: int64

7. What are the mean, median, minimum, maximum, and standard deviation of each numerical column?

In [56]:
nifty50_all_data.describe()

,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
count,235192.000000,235192.000000,235192.000000,235192.000000,235192.000000,235192.000000,235192.00000,2.351920e+05,2.351920e+05,1.203440e+05,2.191150e+05,219115.000000
mean,1266.196349,1267.759708,1286.581440,1247.488465,1266.388302,1266.554351,1267.13230,3.045903e+06,1.610138e+14,6.196427e+04,1.315098e+06,0.502997
std,2581.370320,2585.259609,2619.649216,2546.621396,2581.392543,2582.140942,2582.69998,7.333981e+06,3.298085e+14,6.866457e+04,2.831670e+06,0.190019
min,0.000000,8.500000,9.750000,8.500000,9.100000,9.150000,9.21000,3.000000e+00,1.047000e+07,1.100000e+01,5.000000e+00,0.023600
25%,274.300000,275.000000,279.500000,269.600000,274.400000,274.350000,274.69750,2.190095e+05,1.612816e+13,2.183400e+04,1.253830e+05,0.364700
50%,566.500000,567.025000,576.900000,556.500000,567.000000,566.700000,566.94000,1.010938e+06,6.832603e+13,4.406800e+04,5.017560e+05,0.511000
75%,1242.200000,1243.312500,1263.000000,1221.650000,1242.900000,1242.400000,1242.66250,3.019851e+06,1.863835e+14,7.893550e+04,1.452233e+06,0.638400
max,32861.950000,33399.950000,33480.000000,32468.100000,32849.000000,32861.950000,32975.24000,4.810589e+08,3.564334e+16,1.643015e+06,2.325307e+08,1.000000

8. Number of records for each stock

In [57]:
nifty50_all_data["Symbol"].value_counts()

Symbol
ASIANPAINT    5306
TITAN         5306
DRREDDY       5306
CIPLA         5306
BPCL          5306
              ...
MUNDRAPORT    1023
TELCO          999
KOTAKMAH       502
SSLT           388
JSWSTL         123
Name: count, Length: 65, dtype: int64

9. Duplicate rows

In [62]:
print(nifty50_all_data.duplicated().sum())

0

10. how many gap between Open and Close?

In [76]:
nifty50_all_data["Gap"] = abs(nifty50_all_data["Open"]- nifty50_all_data["Close"])

In [77]:
nifty50_all_data[["Symbol","Gap"]].groupby("Symbol").max()

                Gap
Symbol
ADANIPORTS    79.55
ASIANPAINT   251.05
AXISBANK     130.55
BAJAJ-AUTO   339.55
BAJAJFINSV  1018.95
...             ...
UTIBANK       50.05
VEDL          20.25
WIPRO       1529.55
ZEEL         119.35
ZEETELE      163.45

[65 rows x 1 columns]

11. Which stock has the highest delivery percentage?

In [7]:
nifty50_all_data.groupby("Symbol")["%Deliverble"].max().sort_values(ascending=False)

Symbol
ASIANPAINT    1.0000
SUNPHARMA     1.0000
BAJAJ-AUTO    1.0000
BAJAJFINSV    1.0000
BAJAUTOFIN    1.0000
               ...
HINDLEVER     0.8571
UPL           0.8419
SSLT          0.7407
TISCO         0.7070
TELCO         0.6593
Name: %Deliverble, Length: 65, dtype: float64

12.Which stock has the highest closing price?

In [6]:
nifty50_all_data[["Symbol","Close"]].max()

Symbol     ZEETELE
Close     32861.95
dtype: object