<h1>Using scikit-learn's</h1>

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression

df = pd.read_csv("E:\\My Projects\\Stock price prediction\\cleaned_stock_data.csv")

In [2]:
df

,Prev Close,Open,Low,Close,VWAP,Volume,Turnover,Deliverable Volume,%Deliverble,High
0,233.05,237.50,237.50,251.70,249.37,4456424,3.506810,1810434.0,0.435039,251.70
1,251.70,258.40,251.30,271.85,263.52,9487878,3.530838,1810434.0,0.435039,271.85
2,271.85,256.65,256.65,282.50,274.79,26833684,3.562015,1810434.0,0.435039,287.90
3,282.50,289.00,289.00,294.35,295.45,15682286,3.548739,1810434.0,0.435039,300.70
4,294.35,295.00,293.00,314.55,308.91,19870977,3.556797,1810434.0,0.435039,317.90
...,...,...,...,...,...,...,...,...,...,...
4144,1572.15,1566.00,1531.00,1537.70,1546.33,9408283,3.581118,3034020.0,0.322500,1567.95
4145,1746.15,1750.00,1716.10,1720.90,1731.86,17521196,3.584078,2789706.0,0.348700,1763.75
4146,1704.10,1720.00,1708.05,1737.60,1730.01,13136706,3.584078,3073568.0,0.234000,1749.00
4147,1737.60,1743.00,1735.05,1760.35,1755.20,13286760,3.584078,3239259.0,0.243800,1767.60
4148,1760.35,1779.80,1768.00,1787.90,1781.69,13584004,3.584078,3420711.0,0.251800,1793.00

In [3]:
X = df.drop(columns=['High'],axis=1)
y = df['High']

In [42]:
X

      Prev Close     Open      Low  ...  Turnover  Deliverable Volume  %Deliverble
0         233.05   237.50   237.50  ...  3.506810           1810434.0     0.435039
1         251.70   258.40   251.30  ...  3.530838           1810434.0     0.435039
2         271.85   256.65   256.65  ...  3.562015           1810434.0     0.435039
3         282.50   289.00   289.00  ...  3.548739           1810434.0     0.435039
4         294.35   295.00   293.00  ...  3.556797           1810434.0     0.435039
...          ...      ...      ...  ...       ...                 ...          ...
4144     1572.15  1566.00  1531.00  ...  3.581118           3034020.0     0.322500
4145     1746.15  1750.00  1716.10  ...  3.584078           2789706.0     0.348700
4146     1704.10  1720.00  1708.05  ...  3.584078           3073568.0     0.234000
4147     1737.60  1743.00  1735.05  ...  3.584078           3239259.0     0.243800
4148     1760.35  1779.80  1768.00  ...  3.584078           3420711.0     0.251800

[4149 rows x 9 columns]

In [4]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train,y_test = train_test_split(X,y,test_size=0.3)

In [5]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [6]:
y_predict = model.predict(X_test)

In [7]:
y_predict

array([845.65766143, 348.52084885, 535.36086745, ..., 284.68065449,
       841.91614038, 855.15447161])

In [8]:
y_test

2619     847.90
23       347.35
997      532.70
2821     872.90
3696    1340.00
         ...
1637    1167.00
1278     550.00
806      283.65
3313     844.00
2372     858.55
Name: High, Length: 1245, dtype: float64

In [10]:
import joblib
joblib.dump(model,'stock_model.pkl')

['stock_model.pkl']

In [49]:
X_test

      Prev Close     Open      Low  ...  Turnover  Deliverable Volume  %Deliverble
3436     1016.00  1018.25  1015.70  ...  3.538792           1932733.0     0.602600
3173      908.05   913.20   913.20  ...  3.541735           1799461.0     0.460600
901       361.30   388.80   355.55  ...  3.513365            590806.0     0.153500
2427      778.25   799.00   795.20  ...  3.542895           2150970.0     0.456200
68        364.55   358.00   346.50  ...  3.540212           1810434.0     0.435039
...          ...      ...      ...  ...       ...                 ...          ...
88        316.75   319.60   313.30  ...  3.511853           1810434.0     0.435039
1464      843.45   850.00   835.25  ...  3.544388           1710982.0     0.361400
3566     1077.65  1080.00  1058.75  ...  3.529642           1069777.0     0.476300
2273     1050.65  1052.50  1040.00  ...  3.531724           1220101.0     0.496200
2508      751.55   747.10   736.00  ...  3.521053           1197296.0     0.498000

[1245 rows x 9 columns]

In [8]:
y_test

1019     589.25
2244     915.00
184      354.70
2576     728.85
207      303.75
         ...
13       324.90
2422     778.00
2061    1131.00
3801     926.00
328      363.00
Name: High, Length: 1245, dtype: float64

In [9]:
y_predict

array([ 593.83610752,  914.19423013,  356.86682192, ..., 1130.28982558,
        925.81229153,  361.43894499])

In [9]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_predict)

18.892047004046855

In [13]:
print(f"m = {model.coef_}")
print(f"c = {model.intercept_}")

m = [-2.42213775e-02  5.56392920e-01 -7.59919415e-01  2.56265165e-01
  9.73647137e-01  3.12094775e-08  1.57077695e+01  2.45758445e-07
 -2.13230667e+00]
c = -54.5560621912407

<h1>Implement Gradient Descent by Hand</h1>

In [14]:
X_train

,Year,Month,Day,Prev Close,Open,Low,Close,VWAP,Volume,Turnover,Deliverable Volume,%Deliverble
3497,2016,6,24,980.45,964.9,933.40,951.45,947.15,5711173,3.553183,3518982.0,0.616200
2401,2011,10,21,838.70,840.0,831.10,835.75,841.53,2364175,3.524125,563838.0,0.238500
2971,2014,3,19,896.45,900.0,895.25,903.00,902.16,3743369,3.539602,2101310.0,0.561300
2907,2013,12,12,882.60,878.0,868.00,870.20,871.63,1300646,3.507407,600439.0,0.461600
3509,2016,7,13,1003.40,1005.2,1004.15,1008.75,1010.89,3409386,3.540192,2187003.0,0.641500
...,...,...,...,...,...,...,...,...,...,...,...,...
941,2003,10,9,455.25,459.0,452.10,455.15,457.88,5438028,3.530718,1468073.0,0.270000
623,2002,6,28,271.75,272.0,267.55,269.40,269.29,1805866,3.485733,421651.0,0.233500
469,2001,11,15,273.20,273.0,272.00,278.05,276.10,2236477,3.489028,1810434.0,0.435039
2456,2012,1,11,736.20,737.9,731.50,748.25,743.19,4842143,3.541445,2180554.0,0.450300
3614,2016,12,30,1065.45,1064.8,1063.10,1082.40,1079.52,3591493,3.543601,2387799.0,0.664800

In [15]:
y_train

3497     964.9
2401     849.2
2971     909.9
2907     880.0
3509    1016.7
         ...
941      463.0
623      272.0
469      279.7
2456     753.0
3614    1085.0
Name: High, Length: 2904, dtype: float64

In [ ]:
import numpy as np

x_close = X_train['Close'].values.astype(float)
y_high = y_train.values.astype(float)
n = len(x_close)

m = 0.0
c = 0.0
lr = 0.01
epochs = 10000

loss_history = []

for i in range(epochs):
    
    curr_y = m*x_close + c
    error = curr_y - y_high
    
    
    dm = (2/n) * np.sum(error * x_close)
    dc = (2/n) * np.sum(error)
    
    m = m - lr*dm
    c = c - lr*dc
    
print(f"M = {m}")
print(f"C = {c}")

M = nan
C = nan

C:\Users\karol\AppData\Local\Temp\ipykernel_25108\3183301045.py:27: RuntimeWarning: invalid value encountered in scalar subtract
  m = m - lr*dm

In [16]:
x_close

array([365.55, 958.5 , 869.75, ..., 996.05, 930.85, 413.4 ])