In [1]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("E:\\My Projects\\Stock price prediction\\cleaned_stock_data.csv")
df

,Prev Close,Open,Low,Close,VWAP,Volume,Turnover,Deliverable Volume,%Deliverble,High
0,233.05,237.50,237.50,251.70,249.37,4456424,3.506810,1810434.0,0.435039,251.70
1,251.70,258.40,251.30,271.85,263.52,9487878,3.530838,1810434.0,0.435039,271.85
2,271.85,256.65,256.65,282.50,274.79,26833684,3.562015,1810434.0,0.435039,287.90
3,282.50,289.00,289.00,294.35,295.45,15682286,3.548739,1810434.0,0.435039,300.70
4,294.35,295.00,293.00,314.55,308.91,19870977,3.556797,1810434.0,0.435039,317.90
...,...,...,...,...,...,...,...,...,...,...
4144,1572.15,1566.00,1531.00,1537.70,1546.33,9408283,3.581118,3034020.0,0.322500,1567.95
4145,1746.15,1750.00,1716.10,1720.90,1731.86,17521196,3.584078,2789706.0,0.348700,1763.75
4146,1704.10,1720.00,1708.05,1737.60,1730.01,13136706,3.584078,3073568.0,0.234000,1749.00
4147,1737.60,1743.00,1735.05,1760.35,1755.20,13286760,3.584078,3239259.0,0.243800,1767.60
4148,1760.35,1779.80,1768.00,1787.90,1781.69,13584004,3.584078,3420711.0,0.251800,1793.00

In [3]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR

In [4]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)

In [5]:
liner_model = LinearRegression()
poly_model = LinearRegression()
SVR_model = SVR(kernel='rbf')

In [6]:
liner_model.fit

In [7]:
X = df.drop(columns=['High'])
y = df['High']

In [8]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=45)

In [9]:
liner_model.fit(X_train , y_train)

LinearRegression()

In [10]:
poly_model.fit(poly.fit_transform(X_train) , y_train)

LinearRegression()

In [11]:
SVR_model.fit(X_train,y_train)

SVR()

In [12]:
y_pred_liner = liner_model.predict(X_test)
y_pred_poly = poly_model.predict(poly.fit_transform(X_test))
y_pred_SVR = SVR_model.predict(X_test)

<h1>RSS, RMSE, R²</h1>

<h3>For liner model</h3>

In [13]:
from sklearn.metrics import mean_squared_error, r2_score

In [14]:
RSS = np.sum((y_test - y_pred_liner) ** 2)

RMSE = np.sqrt(mean_squared_error(y_test, y_pred_liner))

R2 = r2_score(y_test, y_pred_liner)

print("RSS :", RSS)
print("RMSE:", RMSE)
print("R²  :", R2)

RSS : 44368.93389865037
RMSE: 5.969731812281231
R²  : 0.9997451628283036

<h3>For Poly. model</h3>

In [15]:
RSS = np.sum((y_test - y_pred_poly) ** 2)

RMSE = np.sqrt(mean_squared_error(y_test, y_pred_poly))

R2 = r2_score(y_test, y_pred_poly)

print("RSS :", RSS)
print("RMSE:", RMSE)
print("R²  :", R2)

RSS : 29327.97940824421
RMSE: 4.853515217495585
R²  : 0.9998315519741574

<h3>For SVR</h3>

In [16]:
RSS = np.sum((y_test - y_pred_SVR) ** 2)

RMSE = np.sqrt(mean_squared_error(y_test, y_pred_SVR))

R2 = r2_score(y_test, y_pred_SVR)

print("RSS :", RSS)
print("RMSE:", RMSE)
print("R²  :", R2)

RSS : 169161042.72649086
RMSE: 368.60863185103665
R²  : 0.028407538749763872

<h1>Check Overfitting / Underfitting</h1>

In [17]:
y_pred_train_liner  = liner_model.predict(X_train)
y_pred_train_poly = poly_model.predict(poly.fit_transform(X_train))
y_pred_train_svr = SVR_model.predict(X_train)

<h3>For liner</h3>

In [18]:
train_score = r2_score(y_train, y_pred_train_liner)

# Test R²
test_score = r2_score(y_test, y_pred_liner)

print("Train Score:", train_score)
print("Test Score :", test_score)

Train Score: 0.9998064930867288
Test Score : 0.9997451628283036

<h3>For poly</h3>

In [19]:
train_score = r2_score(y_train, y_pred_train_poly)

# Test R²
test_score = r2_score(y_test, y_pred_poly)

print("Train Score:", train_score)
print("Test Score :", test_score)

Train Score: 0.9998400102727365
Test Score : 0.9998315519741574

<h3>For SVR</h3>

In [20]:
train_score = r2_score(y_train, y_pred_train_svr)

# Test R²
test_score = r2_score(y_test, y_pred_SVR)

print("Train Score:", train_score)
print("Test Score :", test_score)

Train Score: 0.02376340408483346
Test Score : 0.028407538749763872

<h1>Compare All Models</h1>

In [21]:
results = pd.DataFrame({
    "Model": ["Linear Regression", "Polynomial Regression", "SVR"],
    "RSS": [
        np.sum((y_test - y_pred_liner) ** 2),
        np.sum((y_test - y_pred_poly) ** 2),
        np.sum((y_test - y_pred_SVR) ** 2)
    ],
    "RMSE": [
        np.sqrt(mean_squared_error(y_test, y_pred_liner)),
        np.sqrt(mean_squared_error(y_test, y_pred_poly)),
        np.sqrt(mean_squared_error(y_test, y_pred_SVR))
    ],
    "R²": [
        r2_score(y_test, y_pred_liner),
        r2_score(y_test, y_pred_poly),
        r2_score(y_test, y_pred_SVR)
    ]
})

results

                   Model           RSS        RMSE        R²
0      Linear Regression  4.436893e+04    5.969732  0.999745
1  Polynomial Regression  2.932798e+04    4.853515  0.999832
2                    SVR  1.691610e+08  368.608632  0.028408